{
 "title": "Meraki Labs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "orgName",
    "label": "Organization",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"orgName\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   {
    "name": "networkId",
    "label": "networkId",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"networkId\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Online Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r._field == \"status\" and \n    r._value == \"online\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Offline Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r._field == \"status\" and \n    r._value == \"offline\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Alerting Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r._field == \"status\" and \n    r._value == \"alerting\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Dormant Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r._field == \"status\" and \n    r._value == \"dormant\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "orgId" },
  {
   "title": "Online Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.orgName == \"${orgName}\" and\n    r._field == \"status\" and \n    r._value == \"online\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Offline Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "repeat": "orgId",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.orgName == \"${orgName}\" and\n    r._field == \"status\" and \n    r._value == \"offline\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Alerting Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.orgName == \"${orgName}\" and\n    r._field == \"status\" and \n    r._value == \"alerting\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Dormant Device Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.orgName == \"${orgName}\" and\n    r._field == \"status\" and \n    r._value == \"dormant\"\n  )\n  |> group() \n  |> count(column: \"_value\") \n"
    }
   ]
  },
  {
   "title": "Pod Device History",
   "type": "state-timeline",
   "gridPos": { "h": 44, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n|> range(start: -12h) \n|> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.orgName == \"${orgName}\" and\n    r._field == \"statusNumerical\"\n    )\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: false)\n  |> yield(name: \"deviceStatusOverTime\")"
    }
   ]
  },
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "repeat": "networkId" },
  {
   "title": "Lab Device History",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"meraki-labs-device-status\")\n|> range(start: -24h) \n|> filter(fn: (r) =>\n    r._measurement == \"demo\" and\n    r.networkId == \"${networkId}\" and\n    r._field == \"statusNumerical\"\n    )\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: false)\n  |> yield(name: \"deviceStatusOverTime\")"
    }
   ]
  }
 ]
}